// Generated by Hermes Agent for bodycam fallback relay throttling.
export const liveRelayFramesPerSecond = 2;
export const liveRelayFrameIntervalMs = Math.round(1000 / liveRelayFramesPerSecond);
export const liveRelayFrameWidth = 360;
export const liveRelayJpegQuality = 0.28;
