// Generated by Hermes Agent for stream chunk media probing.
export type StreamChunkProbe = {
  streams?: Array<{ codec_type?: string }>;
};

export const noVideoStreamChunkMessage = "Uploaded browser chunk did not contain video frames yet; waiting for camera video.";

export function parseFfprobeJson(stdout: string): StreamChunkProbe {
  try {
    const parsed = JSON.parse(stdout) as StreamChunkProbe;
    if (!Array.isArray(parsed.streams)) return { streams: [] };
    return { streams: parsed.streams.map((stream) => ({ codec_type: typeof stream.codec_type === "string" ? stream.codec_type : undefined })) };
  } catch {
    return { streams: [] };
  }
}

export function hasVideoStream(probe: StreamChunkProbe) {
  return probe.streams?.some((stream) => stream.codec_type === "video") ?? false;
}
